### ISSUE TITLE
nginx/gunicorn or apache

### ISSUE THREAD

**Issue by matthewhanson** [terranodo/landscapeportal#9]
I've been using nginx/gunicorn for the last couple of years now with GeoNode.   There is no requirement for the web server.   I'm fine with either one, though lean to nginx/gunicorn.

Either way, template config files for the selected web server (and application server in the case of gunicorn) should be included in a geosites_template/config directory.

**Comment by jj0hns0n** [comment]
+1 on nginx/gunicorn if the setup is documented and scripted. Lets confirm with Erick.

**Comment by jj0hns0n** [comment]
@eomwandho this is your decision

**Comment by matthewhanson** [comment]
using nginx and gunicorn

**Comment by eomwandho** [comment]
We don't mind using either nginx or gunicorn for performance reasons, as long as setup is well documented and we would be able to do some configuration similar to old Apache like proxy pass etc. I'm not familiar with gunicorn so I will lean more towards nginx

**Comment by matthewhanson** [comment]
gunicorn is the application server and is used with nginx which is the web server.

With apache there is a wsgi module for that, but with nginx you use a separate application server.

nginx configuration is just as easy as apache, no problem setting that up.
